fixes in zip-dirtree-elements

diff --git a/felix-debian12/user-dotfiles/.local/bin/zip-dirtree-elements b/felix-debian12/user-dotfiles/.local/bin/zip-dirtree-elements
--- a/felix-debian12/user-dotfiles/.local/bin/zip-dirtree-elements
+++ b/felix-debian12/user-dotfiles/.local/bin/zip-dirtree-elements
@@ -1,26 +1,56 @@
 #!/usr/bin/env bash
 
-function trace_fail(){
+function print_error(){
 	if [[ $# -lt 1 ]]; then return; fi
-	FAIL_MESSAGE="${1}"
-	printf "[FAIL] ${1}\n" "${@:2}" 2>&1
+	printf "[ERROR] ${1}\n" "${@:2}" 2>&1
 }
-function trace_info(){
+function print_info(){
 	if [[ $# -lt 1 ]]; then return; fi
-	INFO_MESSAGE="${1}"
 	printf "[INFO] ${1}\n" "${@:2}"
 }
-function trace_debug(){
+function print_debug(){
 	if [[ $# -lt 1 ]]; then return; fi
-	DEBUG_MESSAGE="${1}"
 	printf "[DEBUG] ${1}\n" "${@:2}"
 }
 
 function print_usage(){
 	cat << EOF
-Usage: $(basename ${BASH_SOURCE}) DEPTH
+Usage: $(basename ${BASH_SOURCE}) [OPTIONS] DEPTH
+Create zip archive for each directory at DEPTH from current working 
+directory. The archive names are made of the sub-path from current 
+working directory (excluded) to the zipped directory with dash 
+character as path separator.
+
+Options:
+  -h	Help
+  -j	Number of parallel zip jobs
 EOF
 }
+
+INTEGER_VALUE_REGEX="^[0-9]+$"
+PARALLEL_JOBS=4
+while getopts ":hj:" ARG; do
+	case "${ARG}" in
+		h)
+			print_usage
+			exit 0
+			;;
+		j)
+			if ! [[ "${OPTARG}" =~ ${INTEGER_VALUE_REGEX} ]]; then
+				print_error "Argument -j should be valued with an integer"
+				print_usage
+				exit 1
+			fi
+			PARALLEL_JOBS="${OPTARG}"
+			;;
+		?)
+			print_error "Unknown option -%s" "${OPTARG}"
+			print_usage
+			exit 1
+			;;
+	esac
+done
+shift $((OPTIND-1))
 
 if [[ "${#}" != 1 ]] || ! [[ "${1}" =~ ${INTEGER_VALUE_REGEX} ]] || [[ "${1}" == 0 ]]; then
 	print_usage
@@ -28,16 +58,15 @@ if [[ "${#}" != 1 ]] || ! [[ "${1}" =~ ${INTEGER_VALUE_REGEX} ]] || [[ "${1}" ==
 fi
 
 ELEMENT_TO_ZIP_DEPTH="${1}"
-ELEMENT_TO_ZIP_LIST="$(find . -mindepth "${ELEMENT_TO_ZIP_DEPTH}" -type d 2>/dev/null)"
+ELEMENT_TO_ZIP_LIST="$(find . -mindepth "${ELEMENT_TO_ZIP_DEPTH}" -maxdepth "${ELEMENT_TO_ZIP_DEPTH}" -type d 2>/dev/null)"
 ELEMENT_TO_ZIP_COUNT="$(printf "${ELEMENT_TO_ZIP_LIST}" | wc -l)"
 
 if [[ "${ELEMENT_TO_ZIP_COUNT}" == 0 ]]; then
-	trace_info "Cannot find ${ELEMENT_TO_ZIP_DEPTH}-level directories"
+	trace_info "Cannot find ${ELEMENT_TO_ZIP_DEPTH}-depth directories"
 	exit 0
 fi
 
-echo "${ELEMENT_TO_ZIP_LIST}"
-
+printf "${ELEMENT_TO_ZIP_LIST}\n"
 CONTINUE="false"
 while true; do
 	read -p "Continue? [y/n] " USER_ANSWER
@@ -56,4 +85,4 @@ while true; do
 done
 if ! ${CONTINUE}; then exit 1; fi
 
-find . -mindepth "${ELEMENT_TO_ZIP_DEPTH}" -type d -exec bash -c 'F=$(echo {}|tr / -|cut -c 3-);printf "zip %s\n" "${F}.zip {}"' \; | parallel -vt --jobs 4
+find . -mindepth "${ELEMENT_TO_ZIP_DEPTH}" -maxdepth "${ELEMENT_TO_ZIP_DEPTH}" -type d -exec bash -c 'F=$(echo {}|tr / -|cut -c 3-);printf "zip -r \"${F}\" \"{}\"\n"' \; | parallel -vt --jobs "${PARALLEL_JOBS}"
